//
//  LocalizationTable.swift
//  TokenHamster
//
//  中文文案表 —— key 为**英文源文案**（与源码字面量逐字一致）。
//  ⚠️ 英文无需表：英文态直接把 key 原样返回，所以英文文案的唯一来源是源码。
//  ⚠️ 插值文案的 key 用 `%@` 占位（`L("%@ tokens total", n)`）。
//
//  ★ 本文件由 `git diff d758772^ d758772`（两版逐行对照）生成后人工复核，
//    新增条目请照同样格式追加；`LocalizationTableTests` 会校验键完整性。
//

import Foundation

enum LocalizationTable {

    /// 简体中文表。命中不到时回退到 key 本身（= 英文原文）。
    nonisolated static let zh: [String: String] = [
        // ---- ★ 本功能新增（设置页 / 偏好文案）----
        "Follow System": "跟随系统",
        "Language": "语言",
        "URL": "URL",
        "Units": "单位",
        // ---- ★ 哨兵文案的「显示译文」 ----
        // ★★ 这三个值在**模型层必须保持英文原值**：
        //    `DashboardViewModel` 用 `resetTimeString != "Available"` 判断状态，
        //    生产端（TokenService / DSHUsageStatsSource）不做本地化。
        //    这里的条目只服务**渲染处**的 `L(snap.resetTimeString)`。
        "Available": "可用",
        "Used up": "已用完",
        "Cumulative": "累计",
        // ---- ★ 两版差异对照（由 d758772 逐行对照生成）----
        " (they failed to load in DSH Desktop) — if you run into trouble, roll back to ": "（曾出现在 DSH Desktop 上加载失败）——若遇到问题，请按安装指南回退到 ",
        "%@ by following the install guide.": "%@。",
        "%@ tokens total": "累计 %@ tokens",
        "%@ · resets in %@": "%@ · 距重置 %@",
        "%@ · resetting soon": "%@即将重置",
        "%@-day": "%@天",
        "%@-hour": "%@小时",
        "(the command produced no output)": "（命令没有输出）",
        "API & Model Management": "API 模型管理",
        "Active %@ day%@": "活跃 %@ 天",
        "Active days": "活跃天数",
        "Add": "添加",
        "Apply": "应用",
        "Array (%@ item%@)": "数组（%@ 项）",
        "Balance": "余额",
        "Cancel": "取消",
        "Claude credentials have expired. Run `claude` to log in again.": "Claude 凭据已过期，请运行 claude 重新登录",
        "Close": "关闭",
        "Continue in background": "在后台继续",
        "Copilot response is not valid JSON": "Copilot 响应不是有效 JSON",
        "Copy command": "复制命令",
        "Could not launch %@: %@": "无法启动 %@：%@",
        "Could not read %@": "无法读取 %@",
        "Could not start codex app-server (is the codex CLI installed?)": "无法启动 codex app-server（未安装 codex CLI？）",
        "Currency": "货币单位",
        "Cursor cookie has expired or is invalid. Paste a new one in settings.": "Cursor cookie 已过期或无效，请在设置中重新粘贴",
        "Cursor usage API HTTP %@": "Cursor 用量接口 HTTP %@",
        "Cursor usage API response error: %@": "Cursor 用量接口响应异常: %@",
        "Custom": "自定义",
        "Custom path": "自定义路径",
        "Cycle": "周期",
        "Daily usage": "每日用量",
        "DeepSeek Balance": "DeepSeek 余额",
        "Details": "详情",
        "Direct API": "API 直连",
        "Downloaded from the npm registry": "从 npm registry 下载",
        "Edit config (JSON)": "编辑配置(JSON)",
        "Endpoint URL": "接口地址",
        "Enter a Coding Plan API key (required by the official usage API)": "请填写 Coding Plan API Key（官方用量接口需要）",
        "Failed to fetch quota": "额度获取失败",
        "Failed to fetch quota (local usage is still valid): %@": "额度获取失败（本地用量仍有效）：%@",
        "Failed to parse JSON. Check the format (keys are field names such as totalTokens, values are path strings).": "JSON 解析失败，请检查格式（键为 totalTokens 等字段名，值为路径字符串）",
        "Failed to parse data: %@": "数据解析失败: %@",
        "Gemini has no public usage API": "Gemini 无公开用量 API",
        "Google Gemini has no public usage API. Pick the “Custom” type in settings to hook up another stats service": "Gemini 官方暂无公开用量 API，请在设置中选择 Custom 类型对接其他统计服务",
        "Hide pet": "关闭桌宠",
        "IDE Tools": "IDE 工具",
        "Install": "安装",
        "Install guide": "安装指南",
        "Install plugin": "安装插件",
        "Install the DSH usage plugin": "安装 DSH 用量插件",
        "Installing, this may take a while…": "正在安装，可能需要一会儿…",
        "Invalid API endpoint URL": "无效的 API 地址",
        "Invalid endpoint URL": "接口地址非法",
        "Invalid or expired API key": "API Key 无效或已过期",
        "Invalid response": "无效响应",
        "Kimi API returned an error: %@": "Kimi 接口返回错误: %@",
        "Kimi Balance": "Kimi 余额",
        "Latest version (latest)": "最新版本（latest）",
        "Local": "本地",
        "Local CLI": "本地 CLI",
        "Local path": "本地路径",
        "Missing required field in JSON: %@": "JSON 中缺少必要字段: %@",
        "Model": "模型",
        "Model list": "模型列表",
        "Name": "名称",
        "Network required": "需要联网",
        "No Claude Code OAuth accessToken found (log in to claude first)": "未找到 Claude Code OAuth accessToken（请先登录 claude）",
        "No Codex login credentials found at %@": "未找到 Codex 登录凭据 %@",
        "No Cursor cookie configured (paste one in settings)": "未配置 Cursor Cookie（请在设置中粘贴）",
        "No data sources yet": "暂无配置",
        "No profile found under ~/.dsh/profiles": "未找到 ~/.dsh/profiles 下的 profile",
        "No settings available yet": "暂无设置项",
        "Not configured": "未配置",
        "Not found": "未找到",
        "OpenRouter Balance": "OpenRouter 余额",
        "Organization ID": "组织 ID",
        "Organization slug": "组织 slug",
        "Paste the WorkosCursorSessionToken cookie from your browser (expires in about a month)": "粘贴浏览器中的 WorkosCursorSessionToken cookie（约 1 个月过期）",
        "Peak %@": "峰值 %@",
        "Plugin ready": "插件已就绪",
        "Poll %@s": "轮询 %@s",
        "Quit TokenHamster": "退出 TokenHamster",
        "Quota": "额度",
        "Quota API HTTP %@: %@": "额度接口 HTTP %@: %@",
        "Quota API response error: %@": "额度接口响应异常: %@",
        "Quota Management": "额度管理",
        "Reads a custom path": "读取自定义路径",
        "Reads cursor.com/api/usage (cookie required)": "读取 cursor.com/api/usage（需 Cookie）",
        "Reads remaining credits from /api/v1/key (a standard key is enough); unlimited-credit keys automatically switch to /credits (requires a management key). Amount only, no token detail.": "读 /api/v1/key 的剩余额度（普通 Key 即可）；无限额度 Key 会自动改读 /credits（需管理密钥）。只含金额，无 token 明细。",
        "Reads the account credit total from /v1/user/info (granted + topped-up). The China site api.siliconflow.cn bills in CNY, the global site .com in USD. Amount only, no token detail.": "读 /v1/user/info 的账户总额度（赠费 + 充值）。国内站 api.siliconflow.cn 计 ¥，国际站 .com 计 $。只含金额，无 token 明细。",
        "Reads the local cache of the dsh-usage-stats plugin (~/.dsh/storages)": "读取 dsh-usage-stats 插件的本地缓存（~/.dsh/storages）",
        "Reads ~/.claude/projects": "读取 ~/.claude/projects",
        "Reads ~/.codex/sessions": "读取 ~/.codex/sessions",
        "Requires a GitHub PAT (read:org)": "需 GitHub PAT（read:org）",
        "Requires the file or directory path of a local jsonl log": "需要指定本机 jsonl 日志的文件或目录路径",
        "Resets in %@ days": "%@ 天后重置",
        "Resets in %@ hour%@": "%@ 小时后重置",
        "Resets tomorrow": "明天重置",
        "Resetting soon": "即将重置",
        "Response is not JSON": "响应非 JSON",
        "Response is not a JSON object": "响应非 JSON 对象",
        "Runs third-party install scripts": "会执行第三方安装脚本",
        "Save": "保存",
        "Secondary check: %@": "二次校验：%@",
        "Settings": "设置",
        "Shows token usage progress": "显示 Token 使用进度",
        "SiliconFlow": "硅基流动 SiliconFlow",
        "SiliconFlow Balance": "SiliconFlow 余额",
        "Subscription": "订阅",
        "The cache file is corrupt — waiting for the plugin to rebuild it": "缓存文件损坏，等待插件重建",
        "The cache is being rebuilt — refresh again shortly": "缓存正在重建，请稍后刷新",
        "The command timed out and was terminated (the install may still be running in the background — check in DSH later).": "命令超时被终止（可能仍在后台安装，请稍后在 DSH 里确认）。",
        "The dsh-usage-stats plugin is not installed": "未安装 dsh-usage-stats 插件",
        "The install did not take effect: the package is still missing from the profile.": "安装没有生效：profile 里仍然找不到这个包。",
        "The latest release has not been verified by this app. Some versions of this plugin were marked deprecated on npm": "最新版未经本应用验证。该插件有版本因缺陷被 npm 标记 deprecated",
        "The plugin data is out of date — restart DSH or upgrade the plugin": "插件数据未更新，请重启 DSH 或升级插件",
        "The plugin is active and its data can be read.": "插件已生效，数据可以读了。",
        "The plugin is installed but has no cache yet — restart DSH": "插件已安装但没有缓存，请重启 DSH",
        "The plugin is installed, but you need to restart DSH before I can read its data (the loader tree is fixed at startup).": "插件已装好，但需要你重启 DSH 我才能读到数据（loader 树在启动时固定）。",
        "The plugin is newer than this app — update TokenHamster": "插件版本比本应用新，请更新 TokenHamster",
        "The response is not a valid JSON object": "响应不是有效的 JSON 字典",
        "The server returned an invalid response": "服务器返回了无效的响应",
        "This app won't restart it for you (that would interrupt your running tasks)": "本应用不会替你重启（会中断你正在跑的任务）",
        "This data source no longer exists": "数据源已不存在",
        "Today's token quota": "今日 Token 额度",
        "Total cost": "总费用",
        "Total tokens": "总 Token",
        "Unknown error": "未知错误",
        "Unknown source": "未知数据源",
        "Updated %@": "更新于 %@",
        "Used": "已使用",
        "Verified version %@": "已验证版本 %@",
        "Version": "版本",
        "View install / rollback / uninstall guide": "查看安装 / 回退 / 卸载指南",
        "Weekly": "周",
        "What gets installed": "安装内容",
        "You can rerun this manually in a terminal:": "可在终端手动重跑：",
        "You must restart DSH afterwards": "装完需要你重启 DSH",
        "Z.ai API returned an error: %@": "Z.ai 接口返回错误: %@",
        "\nResponse body: %@": "\n响应内容：%@",
        "auth.json only contains an API key, so the subscription quota can't be queried (use `codex login`)": "auth.json 仅有 API key，无法查询订阅额度（请使用 codex login 登录）",
        "codex RPC exited early": "codex RPC 提前退出",
        "codex RPC response is missing result": "codex RPC 响应缺少 result",
        "codex RPC timed out (15s); the codex process was terminated": "codex RPC 超时（15s），已终止 codex 进程",
        "key = field name, value = JSON path (leave blank if unused)": "键 = 字段名，值 = JSON 路径（未用到留空）",
        "model-usage is missing data.modelDataList": "model-usage 缺少 data.modelDataList",
        "model-usage is missing the data.x_time timeline": "model-usage 缺少 data.x_time 时间轴",
        "npm lifecycle scripts run as your user": "npm lifecycle scripts 会以你的身份运行",
        "org (GitHub organization slug)": "org（GitHub 组织 slug）",
        "organizationId (Anthropic organization ID)": "organizationId（Anthropic 组织 ID）",
        "quota/limit is missing the data.limits array": "quota/limit 缺少 data.limits 数组",
        "quota/limit returned no recognizable quota windows": "quota/limit 未返回可识别的额度窗口",
        "~/.codex/auth.json is missing access_token (log in to codex again)": "~/.codex/auth.json 缺少 access_token（请重新登录 codex）",
        "❌ Endpoint not found (404)\nRequest: %@%@\nHint: check that the protocol type is correct": "❌ 接口不存在 (404)\n请求：%@%@\n提示：检查协议选择是否正确",
        "❌ Failed to parse data: %@": "❌ 数据解析失败：%@",
        "❌ Invalid endpoint URL": "❌ 接口地址格式无效",
        "❌ Invalid or unauthorized API key": "❌ API Key 无效或未授权",
        "❌ Missing field in JSON: %@": "❌ JSON 中缺少字段：%@",
        "❌ Network request failed: %@": "❌ 网络请求失败：%@",
        "❌ Server error %@\nRequest: %@%@": "❌ 服务器错误 %@\n请求：%@%@",
        "❌ The server returned an unexpected response": "❌ 服务器返回了意外的响应",
        "❌ Unknown error: %@": "❌ 未知错误：%@",
    ]
}
